### ISSUE TITLE
数据集请求

### ISSUE THREAD

**Issue by soga12332rbnfj** [541892537/-#1]
请问可以提供用于分类的图像数据集吗？

**Comment by Mrcold2002** [comment]
很抱歉，我换电脑了，这个的数据已经丢失了

**Comment by soga12332rbnfj** [comment]
好的，还是感谢您，我已经找到可以替代的数据集了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月1日(周日) 晚上9:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mrcold2002/Image-information-entropy] 数据集请求 (Issue #1)




 
很抱歉，我换电脑了，这个的数据已经丢失了
